- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
  - name: 'Install requirements'
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl 
      - software-properties-common
      update_cache: yes
      
  - name: 'Add Docker Apt Key'
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      
  - name: 'Add Docker Apt Repository'
    apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
       state: present
       
  - name: 'Update apt and install docker-ce'
    apt: 
      name: docker-ce
      state: latest
      update_cache: yes
            
  - name: 'Run Docker'
      service:
        name: docker
        state: started
